{% set name = "plotext" %}
{% set version = "5.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plotext-{{ version }}.tar.gz
  sha256: 8e81473f57aefdb1234ac897837fd4a4ab9c340acb9c326d63ae7a34d12d45b8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - plotext = plotext.plotext_cli:main

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6

test:
  imports:
    - plotext
  requires:
    - pip
  commands:
    - pip check
    - plotext --help

about:
  home: https://github.com/piccolomo/plotext
  summary: plotext plots data directly on terminal
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
