{% set name = "plotext" %}
{% set version = "4.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plotext-{{ version }}.tar.gz
  sha256: fccb794238f9001d835b158ae2a1f540757a58d4ebb406d99bd68f75f5f7a81e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - plotext = plotext.plotext_cli:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  source_files:
    - tests
  imports:
    - plotext
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - plotext --help
    - pytest -vvv --capture=tee-sys tests

about:
  home: https://github.com/piccolomo/plotext
  summary: plotext plots data directly on terminal
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
