{% set name = "plotext" %}
{% set version = "4.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plotext-{{ version }}.tar.gz
  sha256: ba0a2870f55b4bbc75a06228b4779bdfd2608f1f43ceb4f8851d9f9a63923ef8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - pillow
    - python >=3.6

test:
  imports:
    - plotext
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/piccolomo/plotext
  summary: plotext plots data directly on terminal
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
