{% set name = "plotext" %}
{% set version = "4.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plotext-{{ version }}.tar.gz
  sha256: eda34b1f3b1cb5aed3d646e5e993cda03b465e7519325f69b95aa6cd26007b0e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pillow
    - python >=3.6

test:
  imports:
    - plotext
  requires:
    - pip
  commands:
    - pip check
    - python -c "import plotext as plt; plt.docstrings()"

about:
  home: https://github.com/piccolomo/plotext
  summary: plotext plots data directly on terminal
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
